#!/bin/sh
#
# Reserve 8 CPUs for this job
#$ -pe parallel 4
# Request 8G of RAM
#$ -l h_vmem=8G
# The path used for the standard output stream of the job
#$ -o /ebio/abt5_projects/Sex_biased_genes_Phaeophyceae/data/
# Merge stdout and stderr. The job will create only one output file which
# contains both the real output and the error messages.
#$ -j y
# Use /bin/bash to execute this script
#$ -S /bin/bash
#Run job from current working directory
#$ -cwd
# Send email when the job begins, ends, aborts, or is suspended
#$ -m beas


input_dir="/ebio/abt5_projects/Sex_biased_genes_Phaeophyceae/Myriotrichia/RNAseq/"
conda activate qcontrol_venv

for f in $input_dir/*.fq.gz
do
fastqc $f
done 
