#!/bin/sh
#
# Reserve 8 CPUs for this job
#$ -pe parallel 4
# Request 8G of RAM
#$ -l h_vmem=8G
# The path used for the standard output stream of the job
#$ -o $HOME/tmp/stdout_of_job
# Merge stdout and stderr. The job will create only one output file which
# contains both the real output and the error messages.
#$ -j y
# Use /bin/bash to execute this script
#$ -S /bin/bash
#Run job from current working directory
#$ -cwd
# Send email when the job begins, ends, aborts, or is suspended
#$ -m beas


input_dir=$(q-src /ebio/abt5_projects/Sex_biased_genes_Phaeophyceae/data/RNA_reads/) || exit 1
conda activate qcontrol_venv

fastqc $input_dir/Dictyota-dichotoma_FEMALE_RNAseq_Replicat1_RunA_R1.fq.gz
