#!/bin/sh
#
# Reserve 8 CPUs for this job
#$ -pe parallel 4
# Request 8G of RAM
#$ -l h_vmem=8G
# The path used for the standard output stream of the job
#$ -o /ebio/abt5_projects/Sex_biased_genes_Phaeophyceae/data/
# Merge stdout and stderr. The job will create only one output file which
# contains both the real output and the error messages.
#$ -j y
# Use /bin/bash to execute this script
#$ -S /bin/bash
#Run job from current working directory
#$ -cwd
# Send email when the job begins, ends, aborts, or is suspended
#$ -m beas

conda activate qcontrol_venv

REFIX="Desmarestia-herbacea_FEMALE_RNAseq"

trimmomatic SE $input_dir/${PREFIX}_Replicat1.fq.gz $input_dir/${PREFIX}_output.fq.gz  ILLUMINACLIP:contaminants.fa:2:30:10 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50 HEADCROP:15


PREFIX="Desmarestia-herbacea_FEMALE_RNAseq"

trimmomatic SE $input_dir/${PREFIX}_Replicat2.fq.gz $input_dir/${PREFIX}_output.fq.gz  ILLUMINACLIP:contaminants.fa:2:30:10 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50 HEADCROP:15


PREFIX="Desmarestia-herbacea_FEMALE_RNAseq"

trimmomatic SE $input_dir/${PREFIX}_Replicat3.fq.gz $input_dir/${PREFIX}_output.fq.gz  ILLUMINACLIP:contaminants.fa:2:30:10 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:50 HEADCROP:15
